DefaultContentLanguage = "en"
copyright = "TrackMedia GCV - BE 0679.938.623"

theme = "Mainroad"

[menu]

        [[menu.main]]
        name = "Gaming PC"
        identifier = "gaming-pc"
        url = "/gaming-pc/"
        weight = 20 


        [[menu.main]]
        name = "Components"
        identifier = "components"
        url = "/components/"
        weight = 30

        [[menu.main]]
        name = "Peripherals"
        identifier = "peripherals"
        url = "/peripherals/"
        weight = 40

        [[menu.main]]
        name = "Knowledge"
        identifier = "knowledge"
        url = "/knowledge/"
        weight = 50


[languages]
  [languages.en]
  	languageCode = "en"
  	languageName = "English (USA)"
    title = "2PWNGear - experts in Gaming PCs"
    weight = 10
    contentDir = "content/en"
    baseURL = "https://www.2pwngear.com"
      [languages.en.params]
      linkedin = "https://linkedin.com/whoever"


  [languages.nl-BE]
    languageCode = "nl-BE"
    languageName = "Nederlands (België)"
    title = "2PWNGear - dé specialist in gaming PC's"
    weight = 20
    baseURL = "https://www.2pwngear.be/nl"
    [languages.nl-BE.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.nl-BE.params.navigation]
        help = "Help"
 
  [languages.fr-BE]
    languageCode = "fr-BE"
    languageName = "Français (Belgique)"

    title = "2PWNGear - le spécialiste de Gaming PC"
    weight = 30
    baseURL = "https://www.2pwngear.be/fr"
    [languages.fr-BE.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.fr-BE.params.navigation]
        help = "Aide"


  [languages.nl-NL]
    languageCode = "nl-NL"
    languageName = "Nederlands (Nederland)"
    title = "2PWNGear - dé specialist in gaming PC's"
    weight = 40
    baseURL = "https://www.2pwngear.nl"
    [languages.nl-NL.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.nl-NL.params.navigation]
        help = "Hulp"
 
