DefaultContentLanguage = "en"
copyright = "TrackMedia GCV - BE 0679.938.623"



theme = "Mainroad"





[languages]
  [languages.en]
  	languageCode = "en"
  	languageName = "English (USA)"
    title = "2PWNGear - experts in Gaming PCs"
    weight = 10
    contentDir = "content/en"
    baseURL = "https://www.2pwngear.com"
      [languages.en.params]
      linkedin = "https://linkedin.com/whoever"
      displayURL = "2PWNGear.com"
      ownedby = "is a property of"
      about = "About"
      privacy = "Privacy"
      contact = "Contact"
      disclaimer = "Advertising policy"

      [languages.en.menu]

        [[languages.en.menu.main]]
        name = "Gaming PC"
        identifier = "gaming-pc"
        url = "/gaming-pc/"
        weight = 20 


        [[languages.en.menu.main]]
        name = "Components"
        identifier = "components"
        url = "/components/"
        weight = 30

        [[languages.en.menu.main]]
        name = "Peripherals"
        identifier = "peripherals"
        url = "/peripherals/"
        weight = 40

        [[languages.en.menu.main]]
        name = "Knowledge"
        identifier = "knowledge"
        url = "/knowledge/"
        weight = 50





  [languages.nl-BE]
    languageCode = "nl-BE"
    languageName = "Nederlands (België)"
    title = "2PWNGear - dé specialist in gaming PC's"
    weight = 20
    baseURL = "https://www.2pwngear.be/nl"
    contentDir = "content/nl-BE"
    
    [languages.nl-BE.params]
      linkedin = "https://linkedin.com/fr/whoever"
      help = "Help"
      displayURL = "2PWNGear.be"
      ownedby = "is een website van"
      about = "Over ons"
      privacy = "Privacy"
      contact = "Contact"
      disclaimer = "Disclaimer"

   [languages.nl-BE.menu]

        [[languages.nl-BE.menu.main]]
        name = "Gaming PC"
        identifier = "gaming-pc"
        url = "/gaming-pc/"
        weight = 20 


        [[languages.nl-BE.menu.main]]
        name = "Componenten"
        identifier = "componenten"
        url = "/componenten/"
        weight = 30

        [[languages.nl-BE.menu.main]]
        name = "Accessoires"
        identifier = "accessoires"
        url = "/accessoires/"
        weight = 40

        [[languages.nl-BE.menu.main]]
        name = "Kennis"
        identifier = "kennis"
        url = "/kennis/"
        weight = 50



  [languages.fr-BE]
    languageCode = "fr-BE"
    languageName = "Français (Belgique)"
    contentDir = "content/nl-FR"
    title = "2PWNGear - le spécialiste de Gaming PC"
    weight = 30
    baseURL = "https://www.2pwngear.be/fr"
    [languages.fr-BE.params]
      linkedin = "https://linkedin.com/fr/whoever"

      help = "Aide"
      displayURL = "2PWNGear.be"
      ownedby = "fait partie de"
      about = "Qui nous sommes"
      privacy = "Vie privrée"
      disclaimer = "Disclaimer"
      contact = "Contact"


  [languages.nl-NL]
    languageCode = "nl-NL"
    languageName = "Nederlands (Nederland)"
    title = "2PWNGear - dé specialist in gaming PC's"
    contentDir = "content/nl-NL"
    weight = 40
    baseURL = "https://www.2pwngear.nl"
    [languages.nl-NL.params]
      linkedin = "https://linkedin.com/fr/whoever"

      help = "Hulp"
      displayURL = "2PWNGear.nl" 
      ownedby = "is een website van"
      about = "Over ons"
      privacy = "Privacy"
      contact = "Contact"
      disclaimer = "Disclaimer"

    [languages.nl-NL.menu]

        [[languages.nl-NL.menu.main]]
        name = "Gaming PC"
        identifier = "gaming-pc"
        url = "/gaming-pc/"
        weight = 20 


        [[languages.nl-NL.menu.main]]
        name = "Componenten"
        identifier = "componenten"
        url = "/componenten/"
        weight = 30

        [[languages.nl-NL.menu.main]]
        name = "Accessoires"
        identifier = "accessoires"
        url = "/accessoires/"
        weight = 40

        [[languages.nl-NL.menu.main]]
        name = "Kennis"
        identifier = "kennis"
        url = "/kennis/"
        weight = 50